version: '3'

services:
  backend:
    build: ./backend
    container_name: erp-backend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - erp-seller-booth-network
    develop:
      watch:
        - action: rebuild
          path: ./backend
          target: /app

networks:
  erp-seller-booth-network:
    driver: bridge