version: '3'

services:
  frontend:
    build: ./client
    container_name: erp-client
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - erp-seller-booth-network
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
        - action: rebuild
          path: ./client/package.json
          target: /app

  backend:
    build: ./backend
    container_name: erp-backend
    ports:
      - "1500:1500"
    restart: always
    networks:
      - erp-seller-booth-network
    develop:
      watch:
        - action: rebuild
          path: ./backend
          target: /app

networks:
  erp-seller-booth-network:
    driver: bridge