name: Build and Push Nodejs Image to Google Cloud Platform
on:
  push:
    branches: [main]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: erp-backend-gcr
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Print Service Account Key Content
      run: echo '${{ env.SERVICE_ACCOUNT }}''
      
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ env.SERVICE_ACCOUNT }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Authenticate Docker to GCR
      run: gcloud auth configure-docker --quiet

    - name: Verify Authentication
      run: gcloud auth list

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest ./backend

    - name: Explicit gcloud login
      run: gcloud auth activate-service-account --key-file=${{ env.SERVICE_ACCOUNT }}

    - name: Tag and Push Docker Image
      env: 
        GIT_TAG: v0.1.0
      run: |-
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
        docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
